Quoter/Quoter.Web/Pages/AppCollections/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Quoter.Shared.Enums;
using Quoter.Web.Data;
using Quoter.Web.Data.Entities;
using Quoter.Web.Services;
using System.ComponentModel.DataAnnotations;

namespace Quoter.Web.Pages.AppCollections
{
	public class CreateModel : PageModel
	{
		private readonly ILogger _logger;
		private readonly ApplicationDbContext _context;
		private readonly IFileUploadService _fileUploadService;

		[BindProperty]
		[Required]
		public string Name { get; set; } = string.Empty;

		[BindProperty]
		public string Description { get; set; } = string.Empty;

		[BindProperty]
		public EnumLanguage Language { get; set; } = EnumLanguage.English;

		[BindProperty]
		[Required]
		public IFormFile FileUpload { get; set; }

		public CreateModel(ILoggerFactory loggerFactory, ApplicationDbContext context, IFileUploadService fileUploadService)
		{
			_logger = loggerFactory.CreateLogger("AppCollections.Create");
			_context = context;
			_fileUploadService = fileUploadService;
		}

		public IActionResult OnGet()
		{
			return Page();
		}

		public async Task<IActionResult> OnPostAsync()
		{
			try
			{
				if (!ModelState.IsValid)
				{
					_logger.LogWarning("An attempt was made to create {entity} with invalid model", nameof(AppCollection));
					return Page();
				}

				string fileName = _fileUploadService.GenerateUniqueFileName(FileUpload.FileName, EnumFileUploadType.AppCollection);
				string filePath = await _fileUploadService.SaveFileUploadAsync(FileUpload, EnumFileUploadType.AppCollection, fileName);

				AppCollection newCollection = new()
				{
					Name = Name,
					Description = Description,
					Path = filePath,
					Language = Language,
					UploadDateTime = DateTime.UtcNow
				};

				_context.AppCollections.Add(newCollection);
				await _context.SaveChangesAsync();

				return RedirectToPage("./Index");
			}
			catch (Exception ex)
			{
				_logger.LogError(ex, "An exception occurred while trying to create a new {entity}", nameof(AppCollection));
				return StatusCode(500);
			}
		}
	}
}

Quoter/Quoter.Web/Pages/AppCollections/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Quoter.Web.Data;
using Quoter.Web.Data.Entities;
using Quoter.Web.Services;
using System.Threading.Tasks;

namespace Quoter.Web.Pages.AppCollections
{
	public class IndexModel : PageModel
	{
		private readonly ILogger _logger;
		private readonly ApplicationDbContext _context;
		private readonly IFileUploadService _fileUploadService;

		public int TotalRecords { get; set; } = 0;

		[BindProperty(SupportsGet = true)]
		public int PageNo { get; set; } = 1;

		[BindProperty(SupportsGet = true)]
		public int PageSize { get; set; } = 10;

		public IList<AppCollection> AppCollections { get; set; } = new List<AppCollection>();

		public IndexModel(ILoggerFactory loggerFactory, ApplicationDbContext context, IFileUploadService fileUploadService)
		{
			_logger = loggerFactory.CreateLogger("AppCollections.Index");
			_context = context;
			_fileUploadService = fileUploadService;
		}

		public async Task OnGet()
		{
			TotalRecords = await _context.AppCollections.CountAsync();

			AppCollections = await _context.AppCollections
				.AsNoTracking()
				.OrderByDescending(c => c.UploadDateTime)
				.Skip((PageNo - 1) * PageSize)
				.Take(PageSize)
				.ToListAsync();
		}

		public async Task<ActionResult> OnGetDownloadAsync(int id)
		{
			try
			{
				AppCollection? collection = await _context.AppCollections
					.AsNoTracking()
					.Where(c => c.Id == id)
					.FirstOrDefaultAsync();

				if (!System.IO.File.Exists(collection?.Path))
				{
					throw new ArgumentException($"File does not exist {collection?.Path} for collection id:{id}");
				}

				byte[] bytes = System.IO.File.ReadAllBytes(collection.Path);
				return File(bytes, "application/octet-stream", Path.GetFileName(collection.Path));
			}
			catch (Exception ex)
			{
				_logger.LogError(ex, "An error occured while a user tried to download a collection id:{}", id);
				return BadRequest();
			}
		}

		public async Task<IActionResult> OnPostDeleteAsync(int id)
		{
			try
			{
				AppCollection? collection = await _context.AppCollections.FirstOrDefaultAsync(c => c.Id == id);

				if (collection is null)
				{
					_logger.LogWarning("An attempt was made to delete {entity} with an invalid {property}={value}", nameof(AppCollection), nameof(AppCollection.Id), id);
					return BadRequest();
				}
				else
				{
					_fileUploadService.Delete(collection.Path);
					_context.AppCollections.Remove(collection);
					await _context.SaveChangesAsync();
				}
				return RedirectToPage();
			}
			catch (Exception ex)
			{
				_logger.LogError(ex, "An exception occured while trying to delete {entity} with {property}={value}", nameof(AppCollection), nameof(AppCollection.Id), id);
				return StatusCode(500);
			}
		}
	}
}

Quoter/Quoter.Web/Pages/AppVersions/Create.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Quoter.Shared.Enums;
using Quoter.Web.Data;
using Quoter.Web.Data.Entities;
using Quoter.Web.Services;
using System.ComponentModel.DataAnnotations;
using System.Text.RegularExpressions;

namespace Quoter.Web.Pages.AppVersions
{
	[Authorize]
	public class CreateModel : PageModel
	{
		private readonly ILogger _logger;
		private readonly IFileUploadService _fileUploadService;
		private readonly ApplicationDbContext _context;

		[BindProperty]
		[Required]
		public string Name { get; set; }

		[BindProperty]
		[Required]
		public string Version { get; set; }

		[BindProperty]
		public string? Description { get; set; }

		[BindProperty]
		public EnumOperatingSystem Os { get; set; }

		[BindProperty]
		[Required]
		public EnumVersionType VersionType { get; set; }

		[BindProperty]
		[Required]
		public IFormFile FileUpload { get; set; }

		public CreateModel(
			ILoggerFactory loggerFactory,
			ApplicationDbContext context,
			IFileUploadService fileVersionsService)
		{
			_logger = loggerFactory.CreateLogger("AppVersions.Create");
			_context = context;
			_fileUploadService = fileVersionsService;
		}

		public IActionResult OnGet()
		{
			return Page();
		}

		public async Task<IActionResult> OnPostAsync()
		{
			try
			{
				if (!ModelState.IsValid || !await IsPostValidAsync())
				{
					_logger.LogWarning("An attempt was made to create {entity} with invalid model", nameof(AppVersion));
					return Page();
				}

				string fileName = _fileUploadService.GenerateUniqueFileName(FileUpload.FileName, EnumFileUploadType.AppVersion);
				string filePath = await _fileUploadService.SaveFileUploadAsync(FileUpload, EnumFileUploadType.AppVersion, fileName);

				AppVersion newVersion = new()
				{
					Name = Name,
					Version = Version,
					Description = Description,
					Type = VersionType,
					Os = Os,
					OriginalFileName = FileUpload.FileName,
					Path = filePath,
					CreationDate = DateTime.UtcNow
				};
				_context.AppVersions.Add(newVersion);
				await _context.SaveChangesAsync();
				return RedirectToPage("./Index");
			}
			catch (Exception ex)
			{
				_logger.LogError(ex, "An exception occured while trying create a new {entity}", nameof(AppVersion));
				return StatusCode(500);
			}
		}

		private async Task<bool> IsPostValidAsync()
		{
			Regex regexVersionFormat = new("^\\d+\\.\\d+\\.\\d+\\.\\d+$");
			if (!regexVersionFormat.IsMatch(Version))
			{
				ModelState.TryAddModelError($"{nameof(Version)}", "Version format is incorrect, example correct format: 1.2.3.4");
			}

			// Comment duplicate. Allow duplicate versions for now, check when "Releasing" for duplicates
			//bool isDuplicateVersion = await _context.AppVersions
			//	.AnyAsync(v => v.Version == Version
			//				&& v.Type == VersionType);
			//if (isDuplicateVersion)
			//{
			//	ModelState.TryAddModelError($"{nameof(Version)}", "A version with the same version and version type already exists");
			//	ModelState.TryAddModelError($"{nameof(VersionType)}", "A version with the same version and version type already exists");
			//	return false;
			//}
			return true;
		}
	}
}

Quoter/Quoter.Web/Pages/ApplicationKeys/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Quoter.Web.Data;
using Quoter.Web.Data.Entities;
using System.ComponentModel.DataAnnotations;

namespace Quoter.Web.Pages.ApplicationKeys
{
	public class CreateModel : PageModel
	{
		private readonly ILogger _logger;
		private readonly ApplicationDbContext _context;

		[BindProperty]
		[Required]
		public string NewKey { get; set; }

		public CreateModel(
			ILoggerFactory loggerFactory,
			ApplicationDbContext context)
		{
			_logger = loggerFactory.CreateLogger("ApplicationKeys.Create");
			_context = context;
		}

		public IActionResult OnGet()
		{
			return Page();
		}

		public async Task<IActionResult> OnPostAsync()
		{
			if (!ModelState.IsValid)
			{
				return Page();
			}
			try
			{
				bool isValidKey = await IsPostValidAsync();
				if (isValidKey)
				{
					await CreateApplicationKeyAsync();
					return RedirectToPage("./Index");
				}
			}
			catch (Exception ex)
			{
				_logger.LogError(ex, "An error occured while trying to create an {entity}", nameof(AppKey));
				return StatusCode(500);
			}
			return Page();
		}

		private async Task CreateApplicationKeyAsync()
		{
			AppKey appKey = new AppKey()
			{
				Key = NewKey
			};
			_context.Add(appKey);
			await _context.SaveChangesAsync();
		}

		private async Task<bool> IsPostValidAsync()
		{
			if (await _context.AppKeys.AnyAsync(k => k.Key == NewKey) == true)
			{
				ModelState.AddModelError(nameof(NewKey), "This key is already in use");
				return false;
			}
			return true;
		}
	}
}

Quoter/Quoter.Web/Pages/AppCollections/Create.cshtml
@page
@using Quoter.Shared.Enums;
@using Quoter.Web.ViewModels.Shared;
@model Quoter.Web.Pages.AppCollections.CreateModel

@{
	ViewData["Title"] = Localizer["Create app collection"];

	BreadCrumbsViewModel breadCrumbs = new(
		Localizer["Create app collection"],
		new RouteViewModel(Localizer["Dashboard"], "/AdminDashboard/Index"),
		new RouteViewModel(Localizer["Application collections"], "/AppCollections/Index")
	);
}
<div class="container">
	@await Html.PartialAsync("_BreadCrumbsPartial", breadCrumbs)
	<div class="container m-1">
		<h2>@Localizer["Create app collection"]</h2>
	</div>
	<div class="container mt-2">
		<form method="post" enctype="multipart/form-data">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<div class="row p-1">
				<div class="col-1">
					<label asp-for="Name" class="control-label"></label>
				</div>
				<div class="col-3">
					<input asp-for="Name" class="form-control" />
					<span asp-validation-for="Name" class="text-danger"></span>
				</div>
			</div>
			<div class="row p-1">
				<div class="col-1">
					<label asp-for="Description" class="control-label"></label>
				</div>
				<div class="col-3">
					<input asp-for="Description" class="form-control" />
					<span asp-validation-for="Description" class="text-danger"></span>
				</div>
			</div>
			<div class="row p-1">
				<div class="col-1">
					<label asp-for="Language" class="control-label"></label>
				</div>
				<div class="col-3">
					<select asp-for="Language" class="form-control" asp-items="Html.GetEnumSelectList<EnumLanguage>()"></select>
					<span asp-validation-for="Language" class="text-danger"></span>
				</div>
			</div>
			<div class="row p-1">
				<div class="col-1">
					<label asp-for="FileUpload" class="control-label"></label>
				</div>
				<div class="col-6">
					<input type="file" asp-for="FileUpload" class="form-control" />
					<span asp-validation-for="FileUpload" class="text-danger"></span>
				</div>
			</div>
			<div class="row p-1">
				<div class="col-2">
					<button type="submit" value="Create" class="btn btn-primary">
						<i class="bi bi-file-plus"></i> Create
					</button>
				</div>
			</div>
		</form>
	</div>
</div>

@section Scripts {
	@{
		await Html.RenderPartialAsync("_ValidationScriptsPartial");
	}
}

Quoter/Quoter.Web/Pages/AppCollections/Index.cshtml
@page
@using Quoter.Web.Data.Entities;
@using Quoter.Web.ViewModels.Shared;
@model Quoter.Web.Pages.AppCollections.IndexModel

@{
	ViewData["Title"] = Localizer["Application collections"];

	BreadCrumbsViewModel breadCrumbs = new(
		Localizer["Application collections"],
		new RouteViewModel(Localizer["Dashboard"], "/AdminDashboard/Index"));
}
<div class="container">

	@await Html.PartialAsync("_BreadCrumbsPartial", breadCrumbs)

	<div class="container m-1">
		<h1>@Localizer["Application collections"]</h1>
	</div>
	<div class="container mt-3">
		<a asp-page="Create" class="btn btn-primary mb-2"><i class="bi bi-file-earmark-plus p-1"></i>@Localizer["Create"]</a>
		<div class="table-responsive">
			<table class="table table-sm table-striped table-hover">
				<thead>
					<tr>
						<th>
							@Html.DisplayNameFor(model => model.AppCollections[0].Id)
						</th>
						<th>
							@Html.DisplayNameFor(model => model.AppCollections[0].UploadDateTime)
						</th>
						<th>
							@Html.DisplayNameFor(model => model.AppCollections[0].Name)
						</th>
						<th>
							@Html.DisplayNameFor(model => model.AppCollections[0].Description)
						</th>
						<th>
							@Html.DisplayNameFor(model => model.AppCollections[0].Language)
						</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					@foreach (var item in Model.AppCollections)
					{
						<tr>
							<td>
								@Html.DisplayFor(modelItem => item.Id)
							</td>
							<td>
								<span class="d-inline-block" tabindex="0" data-bs-toggle="popover" data-bs-placement="top" data-bs-trigger="hover focus" data-bs-content="Date time is in UTC">
									@item.UploadDateTime.ToString("yyyy-MM-dd HH:mm:ss")
								</span>
							</td>
							<td>
								@Html.DisplayFor(modelItem => item.Name)
							</td>
							<td>
								@Html.DisplayFor(modelItem => item.Description)
							</td>
							<td>
								@Html.DisplayFor(modelItem => item.Language)
							</td>
							<td>
								<span class="d-inline-block" tabindex="0" data-bs-toggle="popover" data-bs-placement="top" data-bs-trigger="hover focus" data-bs-content="Download">
									<a asp-page="./Index" asp-page-handler="Download" asp-route-id="@item.Id" class="btn btn-sm btn-primary"><i class="bi bi-download"></i></a>
								</span>
								<span class="d-inline-block" tabindex="0" data-bs-toggle="popover" data-bs-placement="top" data-bs-trigger="hover focus" data-bs-content="Delete">
									<button type="button" class="btn btn-sm btn-danger" data-bs-toggle="modal" data-bs-target="#modalDelete" data-bs-name="@item.Name" data-bs-action="/AppCollections/Index?handler=Delete&id=@item.Id.ToString()">
										<i class="bi bi-trash"></i>
									</button>
								</span>
							</td>
						</tr>
					}
				</tbody>
			</table>
			<paging page-no="Model.PageNo"
					page-size="Model.PageSize"
					total-records="Model.TotalRecords"
					url-template="./AppCollections?PageNo={0}&PageSize={1}"
					render-mode="Bootstrap5">
			</paging>
		</div>
	</div>
</div>

<!-- Modal -->
@await Html.PartialAsync(
			"_ModalDeletePartial",
			new ModalDeleteViewModel(Localizer["ConfirmDelete"], Localizer["ConfirmDeleteVersion"]))

@section Scripts {
	<script src="~/js/modal-delete.js"></script>
}