Quoter/Quoter.Web/ViewModels/Shared/BreadCrumbsViewModel.cs
namespace Quoter.Web.ViewModels.Shared
{
	/// <summary>
	/// ViewModel for displaying breadcrumbs and their names and routes
	/// </summary>
	public class BreadCrumbsViewModel
	{
		/// <summary>
		/// The current page name (the last "crumb" in the bread crumbs unclickable)
		/// </summary>
		public string CurrentPageName { get; set; }

		/// <summary>
		/// The routes that the user can go to between Home and Current page
		/// </summary>
		public IEnumerable<RouteViewModel> Routes { get; set; }

		public BreadCrumbsViewModel(string currentPageName)
		{
			CurrentPageName = currentPageName;
			Routes = new List<RouteViewModel>();
		}

		public BreadCrumbsViewModel(string currentPageName, params RouteViewModel[] routes)
		{
			CurrentPageName = currentPageName;
			Routes = routes;
		}
	}
}

Quoter/Quoter.Web/ViewModels/Shared/ModalDeleteViewModel.cs
namespace Quoter.Web.ViewModels.Shared
{
	/// <summary>
	/// View model for a delete modal with delete and cancel options
	/// </summary>
	public class ModalDeleteViewModel
	{
		/// <summary>
		/// Title of the modal.  Should be localized beforehand
		/// </summary>
		public string Title { get; set; }

		/// <summary>
		/// Message of the modal. Should be localized beforehand
		/// </summary>
		public string Message { get; set; }

		public ModalDeleteViewModel(string title, string message)
		{
			Title = title;
			Message = message;
		}
	}
}

Quoter/Quoter.Web/ViewModels/Shared/RouteViewModel.cs
namespace Quoter.Web.ViewModels.Shared
{
	/// <summary>
	/// View model for a route that the user can access
	/// </summary>
	public class RouteViewModel
	{
		/// <summary>
		/// Displayed name of the route
		/// </summary>
		public string Name { get; set; }

		/// <summary>
		/// The route of the page that can be accessed
		/// Ex: /Dashboard/AppVersions/Index
		/// </summary>
		public string Route { get; set; }

		public RouteViewModel(string name, string route)
		{
			Name = name;
			Route = route;
		}
	}
}

Quoter/Quoter.Web/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Caching.Memory;
using Quoter.Shared.Enums;
using Quoter.Web.Data;
using Quoter.Web.Data.Entities;

namespace Quoter.Web.Pages
{
	/// <summary>
	/// Home page of the website
	/// </summary>
	public class IndexModel : PageModel
	{
		private readonly ILogger _logger;
		private readonly ApplicationDbContext _context;
		private readonly IMemoryCache _memoryCache;
		private readonly SignInManager<ApplicationUser> _signInManager;

		/// <summary>
		/// Indicates if any setup file is available for download
		/// </summary>
		public bool IsDownloadAvailable { get; set; } = false;

		/// <summary>
		/// The total number of downloads of any of the versions
		/// </summary>
		public int DownloadsCount { get; set; } = 0;

		public string CurrentCulture { get; set; } = "en-US";

		public IndexModel(
			ILoggerFactory loggerFactory,
			ApplicationDbContext context,
			IMemoryCache memoryCache,
			SignInManager<ApplicationUser> signInManager)
		{
			_logger = loggerFactory.CreateLogger("Index");
			_context = context;
			_memoryCache = memoryCache;
			_signInManager = signInManager;
		}

		public async Task OnGet()
		{
			CurrentCulture = Request.HttpContext.Features.Get<IRequestCultureFeature>()?.RequestCulture.Culture.Name ?? "en-US";

			IsDownloadAvailable = await _memoryCache.GetOrCreateAsync(Constants.MemoryCacheKeys.IsDownloadAvailable,
				async entry =>
			{
				entry.AbsoluteExpirationRelativeToNow = TimeSpan.FromMinutes(15);
				return await _context.AppVersions
					.Where(v => v.IsReleased 
						&& (v.Type == EnumVersionType.Installer || v.Type == EnumVersionType.ZipArchive))
					.AnyAsync();
			});

			if(!IsDownloadAvailable)
			{
				_logger.LogInformation("No download available for the latest version.");
			}

			DownloadsCount = await _memoryCache.GetOrCreateAsync(Constants.MemoryCacheKeys.DownloadsCount,
				async entry =>
				{
					entry.AbsoluteExpirationRelativeToNow = TimeSpan.FromMinutes(60);
					return await _context.AppVersionDownloads.CountAsync();
				});

			await LogVisitAsync();
			
		}

		private async Task LogVisitAsync()
		{
			try
			{
				_context.Visits.Add(new Visit()
				{
					IpAddress = Request.HttpContext.Connection.RemoteIpAddress?.ToString() ?? "Unknown",
					Url = Request.Path,
					VisitDate = DateTime.UtcNow,
				});
				await _context.SaveChangesAsync();
			}
			catch (Exception ex)
			{
				_logger.LogError(ex, "An error occurred while logging visit to the website.");
			}
		}

		/// <summary>
		/// Returns the file for the latest version of the application installer
		/// </summary>
		public async Task<ActionResult> OnGetDownloadApp()
		{
			try
			{
				AppVersion latestVersion = await GetLatestVersionAsync();
				byte[] bytes = System.IO.File.ReadAllBytes(latestVersion.Path);

				_context.AppVersionDownloads
					.Add(new AppVersionDownload
					{
						AppVersionId = latestVersion.Id,
						DownloadDateTime = DateTime.UtcNow,
					});
				await _context.SaveChangesAsync();

				return File(bytes, "application/octet-stream", latestVersion.OriginalFileName);
			}
			catch (Exception ex)
			{
				_logger.LogError(ex, "An error occured while a user tried to download latest version from website.");
				return BadRequest();
			}
		}

		/// <summary>
		/// Sets the culture of the client in a cookie. Used to chance the website language
		/// </summary>
		/// <param name="culture">Culture to change language to (ex: en-US)</param>
		/// <param name="returnUrl">In case we are on different page to return to the same page</param>
		public IActionResult OnPostSetCulture(string culture, string returnUrl)
		{
			Response.Cookies.Append(
				CookieRequestCultureProvider.DefaultCookieName,
				CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
				new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) });

			return LocalRedirect(returnUrl);
		}

		public async Task<IActionResult> OnPostLogoutAsync(string returnUrl)
		{
			await _signInManager.SignOutAsync();
			_logger.LogInformation("User logged out.");
			if (returnUrl != null)
			{
				return LocalRedirect(returnUrl);
			}
			else
			{
				// This needs to be a redirect so that the browser performs a new
				// request and the identity for the user gets updated.
				return RedirectToPage();
			}
		}

		/// <summary>
		/// Retrieves the latest released installer version and verifies file existence.
		/// </summary>
		private async Task<AppVersion> GetLatestVersionAsync()
		{
			AppVersion? latestVersion = await _memoryCache.GetOrCreateAsync(Constants.MemoryCacheKeys.LatestAppVersionForDownload, async entry =>
			{
				entry.AbsoluteExpirationRelativeToNow = TimeSpan.FromMinutes(60);
				entry.SlidingExpiration = TimeSpan.FromMinutes(5);
				return await _context.AppVersions
					.Where(v => v.IsReleased && (v.Type == EnumVersionType.Installer || v.Type == EnumVersionType.ZipArchive))
					.OrderBy(v => v.Id)
					.LastOrDefaultAsync();
			});

			if (latestVersion == null)
			{
				throw new ArgumentException("Latest version is null.");
			}
			if (!System.IO.File.Exists(latestVersion.Path))
			{
				throw new ArgumentException($"File does not exist {latestVersion.Path}");
			}
			return latestVersion;
		}
	}
}

Quoter/Quoter.Web/Pages/Shared/_BreadCrumbsPartial.cshtml
@using Quoter.Web.ViewModels.Shared
@model Quoter.Web.ViewModels.Shared.BreadCrumbsViewModel


<div class="container my-0">
	<nav aria-label="breadcrumb">
		<ol class="breadcrumb breadcrumb-chevron p-2 bg-body-tertiary rounded-3">
			<li class="breadcrumb-item">
				<a class="link-body-emphasis" href="/">
					<i class="bi bi-house-door-fill"></i>
				</a>
			</li>
			@foreach (RouteViewModel route in Model.Routes)
			{
				<li class="breadcrumb-item">
					<a class="link-body-emphasis fw-semibold text-decoration-none" href=@route.Route>@route.Name</a>
				</li>
			}
			<li class="breadcrumb-item active" aria-current="page">
				@Model.CurrentPageName
			</li>
		</ol>
	</nav>
</div>

Quoter/Quoter.Web/Pages/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore.Localization;
@using Microsoft.Extensions.Localization;
@using Quoter.Web.Data.Entities;
@using Quoter.Web.Services;
@using System.Security.Claims
@using System.Reflection
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@inject IStringLocalizer<SharedResource> Localizer
@inject Services.VersionProvider VersionProvider

@{
	string returnUrl = string.IsNullOrEmpty(Context.Request.Path) ? "~/" : $"~{Context.Request.Path.Value}";
	IRequestCultureFeature? requestCultureFeature = Context.Features.Get<IRequestCultureFeature>();
	string culture = "en-US";
	if (requestCultureFeature is not null)
	{
		culture = requestCultureFeature.RequestCulture.Culture.Name;
	}

	//string version = Assembly.GetExecutingAssembly()?.GetCustomAttribute<AssemblyFileVersionAttribute>()?.Version ?? "0.0.0.0";
}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - Minute Verse</title>

	<meta name="description" content="">
	<meta name="keywords" content="">

	<link href="~/images/mv-logo-64.png" rel="icon">

	<!-- Fonts -->
	<link href="https://fonts.googleapis.com" rel="preconnect">
	<link href="https://fonts.gstatic.com" rel="preconnect" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Raleway:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Ubuntu:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap" rel="stylesheet">

	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	@*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

	<link rel="stylesheet" href="~/Quoter.Web.styles.css" asp-append-version="true" />*@

	@* <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous"> *@
	@* <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css"> *@


	<link href="~/lib/enno/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
	<link href="~/lib/enno/bootstrap-icons/bootstrap-icons.min.css" rel="stylesheet" />
	<link href="~/lib/enno/aos/aos.css" rel="stylesheet" />
	<link href="~/lib/enno/glightbox/css/glightbox.css" rel="stylesheet" />
	<link href="~/lib/enno/swiper/swiper-bundle.min.css" rel="stylesheet" />

	<link href="~/css/enno.css" rel="stylesheet" />
	<script src="~/js/scrambler.js"></script>
</head>
<body class="index-page">

	@* -- HEADER -- *@
	<header id="header" class="header d-flex align-items-center sticky-top">
		<div class="container-fluid container-xl position-relative d-flex align-items-center">
			<a href="index" class="logo d-flex align-items-center me-auto">
				<!-- Uncomment the line below if you also wish to use an image logo -->
				@* <img width="40" height="40" src="~/images/minuteverselogosmall.png" /> *@
				<h1 class="sitename">Minute Verse</h1>
			</a>

			<nav id="navmenu" class="navmenu">
				<ul>
					<li><a asp-page="/Index" asp-fragment="home" class="active">@Localizer["Home"]</a></li>
					<li><a asp-page="/Index" asp-fragment="about" class="active">@Localizer["About"]</a></li>
					<li><a asp-page="/Index" asp-fragment="features" class="active">@Localizer["Features"]</a></li>
					@if (SignInManager.IsSignedIn(User))
					{
						<li><a asp-page="/AdminDashboard/Index"><i class="bi bi-table m-1"></i>@Localizer["Admin Dashboard"]</a></li>
					}
					@if (SignInManager.IsSignedIn(User))
					{
						<li class="dropdown">
							<a href="#">
								<i class="bi bi-person-circle m-1"></i>
								@User.Identity?.Name
								<i class="bi bi-chevron-down toggle-dropdown"></i>
							</a>
							<ul>
								<form method="post">
								<li>
									<form class="form-inline" method="post">
										<button class="btn text-danger" asp-page="/Index" asp-page-handler="Logout" type="submit">Logout</button>
									</form>
								</li>
								</form>
							</ul>
						</li>
					}
					<li class="dropdown">@await Html.PartialAsync("_SetCulturePartial", new { culture, returnUrl })</li>
					@if (SignInManager.IsSignedIn(User))
					{
						<p class="text-secondary mt-3">@VersionProvider.Version</p>
					}
				</ul>
				<i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
			</nav>

		</div>
	</header>

	@* -- BODY -- *@
	<main class="main">
		@RenderBody()
	</main>

	@* -- FOOTER -- *@
	<footer id="footer" class="footer">
		<div class="container footer-top">
			<div class="row gy-4">
				<div class="col-lg-4 col-md-6 footer-about">
					<a href="index" class="d-flex align-items-center">
						<span class="sitename">Minute Verse</span>
					</a>
					<div class="footer-contact pt-3">
						<p>@Localizer["Build faith"]</p>
						<p>@Localizer["One verse at a time."]</p>
					</div>
				</div>
				<div class="col-lg-2 col-md-3 footer-links">
					<h4>@Localizer["Useful links"]</h4>
					<ul>
						@switch (culture)
						{
							case "en-US":
								<li><i class="bi bi-chevron-right"></i> <a href="https://www.biblegateway.com/">Bible Gateway</a></li>
								break;
							case "fr-FR":
								<li><i class="bi bi-chevron-right"></i> <a href="https://www.bibliacatolica.com.br/">Biblia</a></li>
								break;
							case "ro-RO":
								<li><i class="bi bi-chevron-right"></i> <a href="https://ebiblia.ro/">eBiblia</a></li>
								<li><i class="bi bi-chevron-right"></i> <a href="https://doxologia.ro/">Doxologia</a></li>
								<li><i class="bi bi-chevron-right"></i> <a href="https://www.bibliaortodoxa.ro/">Biblia ortodxă</a></li>
								<li><i class="bi bi-chevron-right"></i> <a href="https://www.resursecrestine.ro/">Resurse Creștine</a></li>
								break;
						}
					</ul>
				</div>

				<div class="col-lg-2 col-md-3 footer-links">
					<h4>@Localizer["AboutUs"]</h4>
					<ul>
						<li><i class="bi bi-chevron-right"></i><a asp-page="Privacy">@Localizer["PrivacyPolicy"]</a></li>
					</ul>
				</div>

				<div class="col-lg-4 col-md-12">
					<h4>@Localizer["Joshua 1:8"]</h4>
					<p>@Localizer["Keep this Book of the Law always..."]</p>
				</div>
			</div>
		</div>

		<div class="container copyright text-center mt-4">
			<p>© <span>Copyright</span> <strong class="px-1 sitename">Minute Verse</strong> <span> @DateTime.Now.Year @Localizer["All Rights Reserved"]</span></p>
			<div class="credits">
				<!-- All the links in the footer should remain intact. -->
				<!-- You can delete the links only if you've purchased the pro version. -->
				<!-- Licensing information: https://bootstrapmade.com/license/ -->
				<!-- Purchase the pro version with working PHP/AJAX contact form: [buy-url] -->
				Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a> Distributed by <a href=“https://themewagon.com>
					ThemeWagon
					<br />
					<a href="https://www.flaticon.com/free-icons/flag" title="flag icons">Flag icons created by Freepik - Flaticon</a>
					<br />
					<a href="https://www.vecteezy.com/free-vector/man-working-on-computer">Man Working On Computer Vectors by Vecteezy</a>
			</div>
		</div>
	</footer>

	<!-- Scroll Top -->
	<a href="#" id="scroll-top" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

	<!-- Preloader -->
	<div id="preloader"></div>

	@*<script src="~/lib/jquery/dist/jquery.min.js"></script>*@
	@*	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>*@
	@* <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script> *@
	<script src="~/lib/enno/bootstrap/js/bootstrap.bundle.min.js"></script>
	<script src="~/lib/enno/php-email-form/validate.js"></script>
	<script src="~/lib/enno/aos/aos.js"></script>
	<script src="~/lib/enno/glightbox/js/glightbox.min.js"></script>
	<script src="~/lib/enno/purecounter/purecounter_vanilla.js"></script>
	<script src="~/lib/enno/imagesloaded/imagesloaded.pkgd.min.js"></script>
	<script src="~/lib/enno/isotope-layout/isotope.pkgd.min.js"></script>
	<script src="~/lib/enno/swiper/swiper-bundle.min.js"></script>

	@*<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/@@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
	<script src="https://unpkg.com/@@popperjs/core@2"></script>*@
	<script src="~/js/site.js" asp-append-version="true"></script>
	<script src="~/js/enno.js"></script>

	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Quoter/Quoter.Web/Pages/Shared/_ModalDeletePartial.cshtml
@using Quoter.Web.ViewModels.Shared;
@model ModalDeleteViewModel

<div class="modal fade" id="modalDelete" tabindex="-1" aria-labelledby="modalDeleteLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h1 class="modal-title fs-5" id="modalDeleteLabel">@Model.Title</h1>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>
			<div class="modal-body">
				<h6 id ="modalDeleteObjectName"class="text-secondary"></h6>
				<p>@Model.Message</p>
				
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">@Localizer["Cancel"]</button>
				<form method="post">
				@*	<input type="hidden" asp-for="ViewModel.Id" />
					<input type="submit" value="Delete" class="btn btn-danger" />*@
					<button id="modalConfirmDeleteButton" type="submit" data-bs-dismiss="modal" class="btn btn-danger">
						<i class="bi bi-trash"></i> @Localizer["Delete"]
					</button>

				</form>
			</div>
		</div>
	</div>
</div>

Quoter/Quoter.Web/Pages/Shared/_SetCulturePartial.cshtml
@using Quoter.Web;
@using Microsoft.Extensions.Localization;
@model dynamic
@inject IStringLocalizer<SharedResource> Localizer

@* For some reason asp tags are not recognized without adding the following line *@
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
	string culture = Model.culture;
	string returnUrl = Model.returnUrl;
}

<a href="#">@* <span>Language</span>  *@
	@switch (culture)
	{
		case "en-US":
			<img width="32" src="~/images/flags/flag_uk_64.png" />
			break;
		case "ro-RO":
			<img width="32" src="~/images/flags/flag_romania_64.png" />
			break;
		case "fr-FR":
			<img width="32" src="~/images/flags/flag_france_64.png" />
			break;
	}
	<i class="bi bi-chevron-down toggle-dropdown"></i>
</a>


<ul>
	<form method="post">
	<li>
		<button class="nav-link text-black" asp-page="/Index" asp-page-handler="SetCulture" asp-route-culture="en-US" asp-route-returnUrl="@returnUrl">
			<img class="p-1" width="32" src="~/images/flags/flag_uk_64.png" /> @Localizer["English"]
		</button>
	</li>
	<li>
		<button class="nav-link text-black" asp-page="/Index" asp-page-handler="SetCulture" asp-route-culture="ro-RO" asp-route-returnUrl="@returnUrl">
			<img class="p-1" width="32" src="~/images/flags/flag_romania_64.png" /> @Localizer["Romanian"]
		</button>
	</li>
	<li>
		<button class="nav-link text-black" asp-page="/Index" asp-page-handler="SetCulture" asp-route-culture="fr-FR" asp-route-returnUrl="@returnUrl">
			<img class="p-1" width="32" src="~/images/flags/flag_france_64.png" /> @Localizer["French"]
		</button>
	</li>
	</form>
</ul>


@* Creates the drop-down for selecting the website culture (language) *@
@* <div class="dropdown">
	<form method="post">
		<a class="dropdown-toggle btn btn-outline-dark me-2" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
			@switch (culture)
			{
				case "en-US":
					<img width="32" src="~/images/flags/flag_uk_64.png" />
					break;
				case "ro-RO":
					<img width="32" src="~/images/flags/flag_romania_64.png" />
					break;
				case "fr-FR":
					<img width="32" src="~/images/flags/flag_france_64.png" />
					break;
			}
		</a>
		<ul class="dropdown-menu">
			<li>
				<button class="nav-link text-black" asp-page="/Index" asp-page-handler="SetCulture" asp-route-culture="en-US" asp-route-returnUrl="@returnUrl">
					<img class="p-1" width="32" src="~/images/flags/flag_uk_64.png" /> @Localizer["English"]
				</button>
			</li>
			<li>
				<button class="nav-link text-black" asp-page="/Index" asp-page-handler="SetCulture" asp-route-culture="ro-RO" asp-route-returnUrl="@returnUrl">
					<img class="p-1" width="32" src="~/images/flags/flag_romania_64.png" /> @Localizer["Romanian"]
				</button>
			</li>
			<li>
				<button class="nav-link text-black" asp-page="/Index" asp-page-handler="SetCulture" asp-route-culture="fr-FR" asp-route-returnUrl="@returnUrl">
					<img class="p-1" width="32" src="~/images/flags/flag_france_64.png" /> @Localizer["French"]
				</button>
			</li>
		</ul>
	</form>
</div> *@