Quoter/Quoter.Web/Pages/Download.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Caching.Memory;
using Quoter.Web.Data.Entities;
using Quoter.Web.Data;
using Quoter.Shared.Enums;
using Microsoft.EntityFrameworkCore;

namespace Quoter.Web.Pages
{
	public class DownloadModel : PageModel
	{
		private readonly ILogger _logger;
		private readonly ApplicationDbContext _context;
		private readonly IMemoryCache _memoryCache;

		public DownloadModel(
			ILoggerFactory loggerFactory,
			ApplicationDbContext context,
			IMemoryCache memoryCache)
		{
			_logger = loggerFactory.CreateLogger("Download");
			_context = context;
			_memoryCache = memoryCache;
		}

		public void OnGet()
		{
		}

		/// <summary>
		/// Returns the file for the latest version of the application installer
		/// </summary>
		public async Task<ActionResult> OnGetDownloadApp()
		{
			try
			{
				AppVersion latestVersion = await GetLatestVersionAsync();
				byte[] bytes = System.IO.File.ReadAllBytes(latestVersion.Path);

				_context.AppVersionDownloads
					.Add(new AppVersionDownload
					{
						AppVersionId = latestVersion.Id,
						DownloadDateTime = DateTime.UtcNow,
					});
				await _context.SaveChangesAsync();

				return File(bytes, "application/octet-stream", latestVersion.OriginalFileName);
			}
			catch (Exception ex)
			{
				_logger.LogError(ex, "An error occured while a user tried to download latest version from website.");
				return BadRequest();
			}
		}

		/// <summary>
		/// Retrieves the latest released installer version and verifies file existence.
		/// </summary>
		private async Task<AppVersion> GetLatestVersionAsync()
		{
			AppVersion? latestVersion = await _memoryCache.GetOrCreateAsync(Constants.MemoryCacheKeys.LatestAppVersionForDownload, async entry =>
			{
				entry.AbsoluteExpirationRelativeToNow = TimeSpan.FromMinutes(60);
				entry.SlidingExpiration = TimeSpan.FromMinutes(5);
				return await _context.AppVersions
					.Where(v => v.IsReleased && (v.Type == EnumVersionType.Installer || v.Type == EnumVersionType.ZipArchive))
					.OrderBy(v => v.Id)
					.LastOrDefaultAsync();
			});

			if (latestVersion == null)
			{
				throw new ArgumentException("Latest version is null.");
			}
			if (!System.IO.File.Exists(latestVersion.Path))
			{
				throw new ArgumentException($"File does not exist {latestVersion.Path}");
			}
			return latestVersion;
		}
	}
}

Quoter/Quoter.Web/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Quoter.Web.Pages
{
	[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
	[IgnoreAntiforgeryToken]
	public class ErrorModel : PageModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

		private readonly ILogger<ErrorModel> _logger;

		public new int StatusCode { get; set; }

		public ErrorModel(ILogger<ErrorModel> logger)
		{
			_logger = logger;
		}

		public void OnGet(int statusCode)
		{
			RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
			StatusCode = statusCode;
		}
	}
}

Quoter/Quoter.Web/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Caching.Memory;
using Quoter.Shared.Enums;
using Quoter.Web.Data;
using Quoter.Web.Data.Entities;

namespace Quoter.Web.Pages
{
	/// <summary>
	/// Home page of the website
	/// </summary>
	public class IndexModel : PageModel
	{
		private readonly ILogger _logger;
		private readonly ApplicationDbContext _context;
		private readonly IMemoryCache _memoryCache;
		private readonly SignInManager<ApplicationUser> _signInManager;

		/// <summary>
		/// Indicates if any setup file is available for download
		/// </summary>
		public bool IsDownloadAvailable { get; set; } = false;

		/// <summary>
		/// The total number of downloads of any of the versions
		/// </summary>
		public int DownloadsCount { get; set; } = 0;

		public string CurrentCulture { get; set; } = "en-US";

		public IndexModel(
			ILoggerFactory loggerFactory,
			ApplicationDbContext context,
			IMemoryCache memoryCache,
			SignInManager<ApplicationUser> signInManager)
		{
			_logger = loggerFactory.CreateLogger("Index");
			_context = context;
			_memoryCache = memoryCache;
			_signInManager = signInManager;
		}

		public async Task OnGet()
		{
			CurrentCulture = Request.HttpContext.Features.Get<IRequestCultureFeature>()?.RequestCulture.Culture.Name ?? "en-US";

			IsDownloadAvailable = await _memoryCache.GetOrCreateAsync(Constants.MemoryCacheKeys.IsDownloadAvailable,
				async entry =>
			{
				entry.AbsoluteExpirationRelativeToNow = TimeSpan.FromMinutes(15);
				return await _context.AppVersions
					.Where(v => v.IsReleased 
						&& (v.Type == EnumVersionType.Installer || v.Type == EnumVersionType.ZipArchive))
					.AnyAsync();
			});

			if(!IsDownloadAvailable)
			{
				_logger.LogInformation("No download available for the latest version.");
			}

			DownloadsCount = await _memoryCache.GetOrCreateAsync(Constants.MemoryCacheKeys.DownloadsCount,
				async entry =>
				{
					entry.AbsoluteExpirationRelativeToNow = TimeSpan.FromMinutes(60);
					return await _context.AppVersionDownloads.CountAsync();
				});

			await LogVisitAsync();
			
		}

		private async Task LogVisitAsync()
		{
			try
			{
				_context.Visits.Add(new Visit()
				{
					IpAddress = Request.HttpContext.Connection.RemoteIpAddress?.ToString() ?? "Unknown",
					Url = Request.Path,
					VisitDate = DateTime.UtcNow,
				});
				await _context.SaveChangesAsync();
			}
			catch (Exception ex)
			{
				_logger.LogError(ex, "An error occurred while logging visit to the website.");
			}
		}

		/// <summary>
		/// Returns the file for the latest version of the application installer
		/// </summary>
		public async Task<ActionResult> OnGetDownloadApp()
		{
			try
			{
				AppVersion latestVersion = await GetLatestVersionAsync();
				byte[] bytes = System.IO.File.ReadAllBytes(latestVersion.Path);

				_context.AppVersionDownloads
					.Add(new AppVersionDownload
					{
						AppVersionId = latestVersion.Id,
						DownloadDateTime = DateTime.UtcNow,
					});
				await _context.SaveChangesAsync();

				return File(bytes, "application/octet-stream", latestVersion.OriginalFileName);
			}
			catch (Exception ex)
			{
				_logger.LogError(ex, "An error occured while a user tried to download latest version from website.");
				return BadRequest();
			}
		}

		/// <summary>
		/// Sets the culture of the client in a cookie. Used to chance the website language
		/// </summary>
		/// <param name="culture">Culture to change language to (ex: en-US)</param>
		/// <param name="returnUrl">In case we are on different page to return to the same page</param>
		public IActionResult OnPostSetCulture(string culture, string returnUrl)
		{
			Response.Cookies.Append(
				CookieRequestCultureProvider.DefaultCookieName,
				CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
				new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) });

			return LocalRedirect(returnUrl);
		}

		public async Task<IActionResult> OnPostLogoutAsync(string returnUrl)
		{
			await _signInManager.SignOutAsync();
			_logger.LogInformation("User logged out.");
			if (returnUrl != null)
			{
				return LocalRedirect(returnUrl);
			}
			else
			{
				// This needs to be a redirect so that the browser performs a new
				// request and the identity for the user gets updated.
				return RedirectToPage();
			}
		}

		/// <summary>
		/// Retrieves the latest released installer version and verifies file existence.
		/// </summary>
		private async Task<AppVersion> GetLatestVersionAsync()
		{
			AppVersion? latestVersion = await _memoryCache.GetOrCreateAsync(Constants.MemoryCacheKeys.LatestAppVersionForDownload, async entry =>
			{
				entry.AbsoluteExpirationRelativeToNow = TimeSpan.FromMinutes(60);
				entry.SlidingExpiration = TimeSpan.FromMinutes(5);
				return await _context.AppVersions
					.Where(v => v.IsReleased && (v.Type == EnumVersionType.Installer || v.Type == EnumVersionType.ZipArchive))
					.OrderBy(v => v.Id)
					.LastOrDefaultAsync();
			});

			if (latestVersion == null)
			{
				throw new ArgumentException("Latest version is null.");
			}
			if (!System.IO.File.Exists(latestVersion.Path))
			{
				throw new ArgumentException($"File does not exist {latestVersion.Path}");
			}
			return latestVersion;
		}
	}
}

Quoter/Quoter.Web/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Quoter.Web.Pages
{
	public class PrivacyModel : PageModel
	{
		private readonly ILogger<PrivacyModel> _logger;

		public PrivacyModel(ILogger<PrivacyModel> logger)
		{
			_logger = logger;
		}

		public void OnGet()
		{
		}
	}
}

Quoter/Quoter.Web/Pages/Download.cshtml
@page
@model Quoter.Web.Pages.DownloadModel
@inject IStringLocalizer<SharedResource> Localizer
@{
	ViewData["Title"] = Localizer["FinishDownload"];
}

<div class="container mt-5">
	<div class="row gy-4 text-center">
		<h1 class="fw-bold mt-">@Localizer["ThankYou"]</h1>
		<p>
			@Localizer["IfDownloadDoesNotStartClick"]
			<a asp-page-handler="DownloadApp" id="download-link" class="fw-bold text-primary">@Localizer["Here"]</a>
		</p>
	</div>
	<div class="row gy-4 mt-5">
		<h2>@Localizer["InstallInfo"]</h2>

		<p><strong class="text-danger fs-3 fw-bold">@Localizer["Important:"]</strong> @Localizer["TheApplicationIsNotSigned"]</p>
		<div class="row">
			<div class="col-lg-4"><img height="380px" src="~/images/tutorial/smart-screen-moreinfo.png" /></div>
			<div class="col-lg-4"><img height="380px" src="~/images/tutorial/smart-screen-runanyway.png" /></div>
		</div>

		<p>@Localizer["FollowTheSetupInstructions"]</p>
		<div class="row">
			<div class="col-lg-4"><img width="420px" src="~/images/tutorial/install-1-select-install-mode.png" /></div>
			<div class="col-lg-4"><img src="~/images/tutorial/install-2-language.png" /></div>
			<div class="col-lg-4"><img width="420px" src="~/images/tutorial/install-3-licence.png" /></div>
			<div class="col-lg-4"><img width="420px" src="~/images/tutorial/install-4-location.png" /></div>
			<div class="col-lg-4"><img width="420px" src="~/images/tutorial/install-5-desktop-shortcut.png" /></div>
			<div class="col-lg-4"><img width="420px" src="~/images/tutorial/install-6-finish.png" /></div>
		</div>
		
		<h2 class="mt-4">@Localizer["AfterInstalation"]</h2>
		<p>@Localizer["ToStartTheApp"]</p>
		<div class="row">
			<div class="col"><img src="~/images/tutorial/tray-icon.png" /></div>
		</div>
	</div>
</div>

@section Scripts {
	<script>
		document.addEventListener("DOMContentLoaded", function() {
			setTimeout(function() {
				document.getElementById("download-link").click();
			}, 2000);
		});
	</script>
}

Quoter/Quoter.Web/Pages/Index.cshtml
@*
	"HOME" Landing page of the website.
	Contains download button and features list
*@
@page
@model IndexModel
@{
	ViewData["Title"] = Localizer["Home"];
}

<section id="home" class="hero section">

	<div class="container">
		<div class="row gy-4">
			<div class="col-lg-6 order-2 order-lg-1 d-flex flex-column justify-content-center" data-aos="fade-up">
				<h1>@Localizer["Build wisdom one verse at a time"]</h1>
				<p>@Localizer["Remind yourself..."]</p>
				<p>@Localizer["Lots of customization options..."]</p>
				<div class="d-flex">
					@if (Model.IsDownloadAvailable)
					{
						<a asp-page="Download" class="btn btn-primary p-2"><i class="bi bi-download p-2"></i>@Localizer["Download for Windows"]</a>
					}
					else
					{
						<div class="btn btn-secondary p-2">@Localizer["Download unavailable at this time"]</div>
					}

				</div>
			</div>
			<div class="col-lg-6 order-1 order-lg-2 hero-img" data-aos="zoom-out" data-aos-delay="100">
				@switch (Model.CurrentCulture)
				{
					case "en-US":
						<img src="~/images/mv-media-en.png" class="img-fluid animated" alt="">
						break;
					case "ro-RO":
						<img src="~/images/mv-media-ro.png" class="img-fluid animated" alt="">
						break;
					case "fr-FR":
						<img src="~/images/mv-media-fr.png" class="img-fluid animated" alt="">
						break;
				}
			</div>
		</div>
	</div>

</section>

<section id="featured-services" class="featured-services section">
	<div class="container">
		<div class="row gy-4">
			<div class="col-lg-4 d-flex" data-aos="fade-up" data-aos-delay="100">
				<div class="service-item position-relative">
					<div class="icon"><i class="bi bi-bell icon"></i></div>
					<h4 class="stretched-link">@Localizer["Periodic notifications"]</h4>
					<p>@Localizer["Receive regular notifications..."]</p>
				</div>
			</div><!-- End Service Item -->

			<div class="col-lg-4 d-flex" data-aos="fade-up" data-aos-delay="200">
				<div class="service-item position-relative">
					<div class="icon"><i class="bi bi-pencil-square icon"></i></div>
					<h4 class="stretched-link">@Localizer["Collections editor"]</h4>
					<p>@Localizer["Create and edit your own..."]</p>
				</div>
			</div><!-- End Service Item -->

			<div class="col-lg-4 d-flex" data-aos="fade-up" data-aos-delay="300">
				<div class="service-item position-relative">
					<div class="icon"><i class="bi bi-share icon"></i></div>
					<h4 class="stretched-link">@Localizer["Export and import"]</h4>
					<p>@Localizer["Export your created collections..."]</p>
				</div>
			</div><!-- End Service Item -->
		</div>
	</div>
</section>

<section id="about" class="about section">
	<!-- Section Title -->
	<div class="container section-title" data-aos="fade-up">
		<span>@Localizer["Who is this for"]<br></span>
		<h2>@Localizer["About"]</h2>
		<p>@Localizer[""]</p>
	</div><!-- End Section Title -->
	<div class="container">
		<div class="row gy-4">
			<div class="col-lg-6 position-relative align-self-start" data-aos="fade-up" data-aos-delay="100">
				<img src="~/images/man-on-computer.jpg" class="img-fluid" alt="">
			</div>
			<div class="col-lg-6 content" data-aos="fade-up" data-aos-delay="200">
				<h3>@Localizer["Do you work on your PC or laptop?"]</h3>
				<p class="fst-italic">
					@Localizer["Then Minute Verse is for you..."]
					@Localizer["Here are some ways you can use the app:"]
				</p>
				<ul>
					<li><i class="bi bi-check2-all"></i> <span>@Localizer["As a reminder..."]</span></li>
					<li><i class="bi bi-check2-all"></i> <span>@Localizer["Learning little by little..."]</span></li>
					<li><i class="bi bi-check2-all"></i> <span>@Localizer["A tool to help you memorize..."]</span></li>
					<li><i class="bi bi-check2-all"></i> <span>@Localizer["Create your own collection..."]</span></li>
				</ul>
				<p>
					@Localizer["Easy to install and use as is..."]
				</p>
			</div>
		</div>
	</div>
</section>

<section id="stats" class="stats section">
	<div class="container" data-aos="fade-up" data-aos-delay="100">
		<div class="row gy-4">
			<div class="col-lg-6 col-md-6">
				<div class="stats-item text-center w-100 h-100">
					<span data-purecounter-start="0" data-purecounter-end="@Model.DownloadsCount" data-purecounter-duration="1" class="purecounter"></span>
					<p>@Localizer["Downloads"]</p>
				</div>
			</div><!-- End Stats Item -->

			<div class="col-lg-6 col-md-6">
				<div class="stats-item text-center w-100 h-100">
					<span data-purecounter-start="0" data-purecounter-end="5" data-purecounter-duration="1" class="purecounter"></span>
					<p>@Localizer["Bible translations"]</p>
				</div>
			</div><!-- End Stats Item -->
		</div>
	</div>
</section>

<section id="features" class="services section light-background">
	<!-- Section Title -->
	<div class="container section-title" data-aos="fade-up">
		<span>@Localizer["Features"]</span>
		<h2>@Localizer["Features"]</h2>
		<p>@Localizer["See below all of the features of the application"]</p>
	</div><!-- End Section Title -->
	<div class="container">

		<div class="row gy-4">

			<div class="col-lg-4 col-md-6" data-aos="fade-up" data-aos-delay="100">
				<div class="service-item position-relative">
					<img class="w-100 p-1" src="~/images/mv-fadein-en.gif" />
					<a href="index" class="stretched-link">
						<h3>@Localizer["Periodic notifications"]</h3>
					</a>
					<p>@Localizer["You can customize the intervals..."]</p>
				</div>
			</div><!-- End Service Item -->

			<div class="col-lg-4 col-md-6" data-aos="fade-up" data-aos-delay="200">
				<div class="service-item position-relative">
					<img class="w-100 p-1" src="~/images/mv-scroll-en.gif" />
					<a href="index" class="stretched-link">
						<h3>@Localizer["Scrollable"]</h3>
					</a>
					<p>@Localizer["Scroll to the next or previous verses..."]</p>
				</div>
			</div><!-- End Service Item -->

			<div class="col-lg-4 col-md-6" data-aos="fade-up" data-aos-delay="300">
				<div class="service-item position-relative">
					<img class="w-100 p-1" src="~/images/mv-opacity-en.gif" />
					<a href="index" class="stretched-link">
						<h3>@Localizer["Customizable opactity"]</h3>
					</a>
					<p>@Localizer["Make the notification window..."]</p>
				</div>
			</div><!-- End Service Item -->

			<div class="col-lg-4 col-md-6" data-aos="fade-up" data-aos-delay="400">
				<div class="service-item position-relative">
					<img class="w-100 p-1" src="~/images/mv-themes-en.jpg" />
					<a href="index" class="stretched-link">
						<h3>@Localizer["Multiple color themes"]</h3>
					</a>
					<p>@Localizer["Choose from a variety of pre-set color..."]</p>
					<a href="index" class="stretched-link"></a>
				</div>
			</div><!-- End Service Item -->

			<div class="col-lg-4 col-md-6" data-aos="fade-up" data-aos-delay="500">
				<div class="service-item position-relative">
					<img class="w-100 p-1" src="~/images/mv-link-en.png" />
					<a href="index" class="stretched-link">
						<h3>@Localizer["Virtual book"]</h3>
					</a>
					<p>@Localizer["Click the chapter and verse to open a simplified reader..."]</p>
					<a href="index" class="stretched-link"></a>
				</div>
			</div><!-- End Service Item -->

			<div class="col-lg-4 col-md-6" data-aos="fade-up" data-aos-delay="600">
				<div class="service-item position-relative">
					<img class="w-100 p-1" src="~/images/mv-pinned-en.png" />
					<a href="index" class="stretched-link">
						<h3>@Localizer["Pinnable notification"]</h3>
					</a>
					<p>@Localizer["If you prefer, the notification window..."]</p>
					<a href="index" class="stretched-link"></a>
				</div>
			</div><!-- End Service Item -->

			<div class="col-lg-4 col-md-6" data-aos="fade-up" data-aos-delay="100">
				<div class="service-item position-relative">
					<div class="icon">
						<i class="bi bi-pencil-square"></i>
					</div>
					<a href="index" class="stretched-link">
						<h3>@Localizer["Integrated editor"]</h3>
					</a>
					<p>@Localizer["Create and edit your own collections using the integrated editor..."]</p>
				</div>
			</div><!-- End Service Item -->

			<div class="col-lg-4 col-md-6" data-aos="fade-up" data-aos-delay="100">
				<div class="service-item position-relative">
					<div class="icon">
						<i class="bi bi-star"></i>
					</div>
					<a href="index" class="stretched-link">
						<h3>@Localizer["Select your favourites"]</h3>
					</a>
					<p>@Localizer["You can select your favourite chapters or books..."]</p>
				</div>
			</div><!-- End Service Item -->

			<div class="col-lg-4 col-md-6" data-aos="fade-up" data-aos-delay="100">
				<div class="service-item position-relative">
					<div class="icon">
						<i class="bi bi-share"></i>
					</div>
					<a href="index" class="stretched-link">
						<h3>@Localizer["Share or import collections"]</h3>
					</a>
					<p>@Localizer["Share your private collections..."]</p>
				</div>
			</div><!-- End Service Item -->

		</div>
	</div>
</section><!-- /Services Section -->
<!-- Call To Action Section -->
<section id="call-to-action" class="call-to-action section accent-background">

	<div class="container">
		<div class="row justify-content-center" data-aos="zoom-in" data-aos-delay="100">
			<div class="col-xl-10">
				<div class="text-center">
					<h3>@Localizer["Download now"]</h3>
					<p>@Localizer["Try it out and see if you like it..."]</p>
					@if (Model.IsDownloadAvailable)
					{
						<a asp-page="Download" class="cta-btn"><i class="bi bi-download p-2"></i>@Localizer["Download for Windows"]</a>
					}
					else
					{
						<div class="cta-btn m">@Localizer["Download unavailable at this time"]</div>
					}
				</div>
			</div>
		</div>
	</div>

</section><!-- /Call To Action Section -->